from graphviz import Digraph

dot = Digraph(comment='Architecture Diagram')

# Add nodes
dot.node('A', 'User/Client')
dot.node('B', 'Login/Register')
dot.node('C', 'Home Page')
dot.node('D', 'Browse Services')
dot.node('E', 'Book Service')
dot.node('F', 'Appointment History')
dot.node('G', 'Feedback')
dot.node('H', 'Worker')
dot.node('I', 'Login/Register')
dot.node('J', 'Worker Home')
dot.node('K', 'View Assigned Tasks')
dot.node('L', 'Mark Completed/Reject')
dot.node('M', 'View Feedbacks')
dot.node('N', 'Admin')
dot.node('O', 'Login')
dot.node('P', 'Admin Dashboard')
dot.node('Q', 'Manage Users')
dot.node('R', 'Manage Workers')
dot.node('S', 'Manage Services')
dot.node('T', 'Manage Locations')
dot.node('U', 'View Requests')
dot.node('V', 'Assign Workers')
dot.node('W', 'View Responses')
dot.node('X', 'View Feedbacks')

# Add edges
dot.edge('A', 'B')
dot.edge('B', 'C')
dot.edge('C', 'D')
dot.edge('D', 'E')
dot.edge('E', 'F')
dot.edge('F', 'G')
dot.edge('H', 'I')
dot.edge('I', 'J')
dot.edge('J', 'K')
dot.edge('K', 'L')
dot.edge('L', 'M')
dot.edge('N', 'O')
dot.edge('O', 'P')
dot.edge('P', 'Q')
dot.edge('P', 'R')
dot.edge('P', 'S')
dot.edge('P', 'T')
dot.edge('P', 'U')
dot.edge('P', 'V')
dot.edge('P', 'W')
dot.edge('P', 'X')

# Render to PNG
dot.render('/workspaces/prjct2026/architecture_diagram', format='png', cleanup=True)

print("Architecture diagram PNG created.")